### PR TITLE
Add UNICODE support in windows based on #19 (Fixes #17)

### LINKED ISSUE #17: Fails on UNICODE builds on Windows
Compiling with the `UNICODE` macro (which is required by most other well-behaving Windows libraries) currently fails.

If you want to be ASCII-only then you must explicitly call the `*A` versions of functions, e.g. `FindFirstFileA` instead of `FindFirstFile`. The unadorned versions are macros that expand to either `FindFirstFileW` or `FindFirstFileA` depending on whether `_UNICODE` is in use or not.

A better bet would be to just be compatible with `_UNICODE` as there are some places where you need Windows' native UTF16 paths and can't use the ASCII variants. To do this you need to use `TCHAR` instead of `char` for your strings and buffers and use the the `TEXT` macro to wrap all your literals.

Yeah, Windows is lame for not just being UTF8 everywhere, but it is what it is. Recommended practice for Win32 developers is to use UTF8 internally for all strings, enable `_UNICODE` to catch mistakes like this one with Win32 calls, to always explicitly call the *W variants of functions (in case a user turns off `_UNICODE`), and then do any translation to and from UTF16/UTF8 at the boundaries where Win32 OS calls are made.

For a library like this one, I think the best option would be to just support both modes using the macros described above.

Errors received with latest tinydir when using `_UNICODE`:

    1>C:\Users\Sean\Documents\Projects\tinydir/tinydir.h(142): error C2664: 'HANDLE FindFirstFileW(LPCWSTR,LPWIN32_FIND_DATAW)' : cannot convert argument 1 from 'char [4096]' to 'LPCWSTR'
    1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
    1>C:\Users\Sean\Documents\Projects\tinydir/tinydir.h(327): error C2664: 'size_t strlen(const char *)' : cannot convert argument 1 from 'const WCHAR [260]' to 'const char *'
    1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
    1>C:\Users\Sean\Documents\Projects\tinydir/tinydir.h(340): error C2664: 'size_t strlen(const char *)' : cannot convert argument 1 from 'const WCHAR [260]' to 'const char *'
    1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
    1>C:\Users\Sean\Documents\Projects\tinydir/tinydir.h(354): error C2664: 'char *strcpy(char *,const char *)' : cannot convert argument 2 from 'const WCHAR [260]' to 'const char *'
    1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

### PR DESCRIPTION
**Pull request by lautis0503**
ALL TEST PASSED. CAN BE MERGED NOW.

### CODE REVIEW

**Comment by cxong** [comment]
Thanks for the PR; could you please come up with some unicode files/folders so this can be tested?

**Comment by lautis0503** [comment]
A sample with Chinese/Japanese/Korean/Russian characters: 
https://mega.nz/#!N0EyQC5I!o2v_zKi3Yz1vgaLxi3q2uxiIEG4U2y0-eNSulzcHE0I

Test passed in fc23 + gcc 5.3.1 using example 1.

**Comment by lautis0503** [comment]
Need to add unicode support for mingw32

**Comment by lautis0503** [comment]
195dcfaa5ff13ec87814c23ca3b9918e3bed3abd
Add support for MINGW32

Test passed in fc23 + gcc 5.3.1.
Test passed in windows 7 + mingw32-gcc-4.9.2.

**Comment by lautis0503** [comment]
2a849cad3ed0794b613c5c16bada89a616619de5
Fix support for VS

Test **PASSED** in fc23 + gcc 5.3.1.
Test **PASSED** in windows 7 + mingw32-gcc-4.9.2.
Test **PASSED** in windows 7 + vs 2010

I don't have a MAC OS, but it should work fine.

PS: README.md need to be changed to support unicode in windows.

**Comment by cxong** [comment]
I will try to find some time to review and merge the changes. I think adding a test suite which exercises the samples will also be good.

**Comment by cxong** [comment]
I've tested the non-unicode version and everything looks ok; however when testing with VS2013, there's incompatible type errors: when `_UNICODE` is defined, functions like `_tcslen` are defined as `wcslen`, which use the `wchar_t` type, but `TCHAR` remains `char`. To have `TCHAR` be `wchar_t`, it expects the `UNICODE` defined instead (note: no underscore). I'm not familiar with this stuff so I'd prefer if you take a look. Maybe these links will help:

- https://blogs.msdn.microsoft.com/oldnewthing/20040212-00/?p=40643
- http://stackoverflow.com/q/2259544/2038264

Here's the full error log:

```
1>------ Build started: Project: list_to_file, Configuration: Debug Win32 ------
1>  list_to_file.c
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(230): error C2220: warning treated as error - no 'object' file generated
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(230): warning C4133: 'function' : incompatible types - from 'const TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(235): warning C4133: 'function' : incompatible types - from 'const TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(253): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(253): warning C4133: 'function' : incompatible types - from 'const TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(255): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(262): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(262): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(263): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(464): warning C4133: 'function' : incompatible types - from 'const TCHAR [4096]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(471): warning C4133: 'function' : incompatible types - from 'const CHAR [260]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(484): warning C4133: 'function' : incompatible types - from 'const CHAR [260]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(490): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(490): warning C4133: 'function' : incompatible types - from 'const TCHAR [4096]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(491): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(492): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(498): warning C4133: 'function' : incompatible types - from 'const CHAR [260]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(499): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(499): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(576): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(576): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(602): warning C4133: 'function' : incompatible types - from 'const TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(607): warning C4133: 'function' : incompatible types - from 'const TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(617): warning C4133: 'function' : incompatible types - from 'const TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(618): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(619): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(620): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(621): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(636): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(636): warning C4133: 'function' : incompatible types - from 'TCHAR [4096]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(639): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(639): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(662): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(662): warning C4133: 'function' : incompatible types - from 'TCHAR *' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(684): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(684): warning C4133: 'initializing' : incompatible types - from 'wchar_t *' to 'TCHAR *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(687): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\tinydir.h(704): warning C4133: 'function' : incompatible types - from 'const TCHAR [256]' to 'const wchar_t *'
1>C:\Users\Cong\Documents\GitHub\tinydir\samples\list_to_file.c(14): warning C4133: 'function' : incompatible types - from 'unsigned short [13]' to 'const TCHAR *'
1>C:\Users\Cong\Documents\GitHub\tinydir\samples\list_to_file.c(22): warning C4996: '_wfopen': This function or variable may be unsafe. Consider using _wfopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(590) : see declaration of '_wfopen'
1>C:\Users\Cong\Documents\GitHub\tinydir\samples\list_to_file.c(33): warning C4133: 'function' : incompatible types - from 'TCHAR [256]' to 'const wchar_t *'
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

**Comment by lautis0503** [comment]
I'm sorry for that.
I found the same problem some time ago, so I define both _UNICODE and UNICODE in my test code(list_to_file.c in my PR).
But users are always right.
I will fix this.

**Comment by cxong** [comment]
Thanks :fireworks:

**Comment by lautis0503** [comment]
**Old samples and README need to be modified**
(Refer to list_to_file.c in my PR)

**Comment by lautis0503** [comment]
It's better to replace & with && in line 35 and 39 of 7f3b2f7706cda06b531f02edb048efefcd518d92.
Wouldn't crash, but looks so strange and informal.

**Comment by lautis0503** [comment]
Test PASSED* in Windows 7 + Cygwin 2.5.2 & GCC 5.4.0 .

**Comment by lautis0503** [comment]
Test PASSED in OS X 10.11.6 + GCC 6.3.0.
Test PASSED in OS X 10.11.6 + Apple LLVM version 7.3.0 (Xcode 7.3).

**Comment by lautis0503** [comment]
Test PASSED in FreeBSD 12.0 + Clang 4.0.0.
Test PASSED in FreeBSD 12.0 + GCC 5.4.0.

Test PASSED in Windows 2000/XP, 95/98(Ansi only, before #50) + MinGW GCC(forgot the version).

**Comment by lautis0503** [comment]
Test PASSED in Red Hat Linux 7.3(kernel 2.4.18) + gcc 2.96. _(JUST FOR FUN!)_

**Comment by lautis0503** [comment]
Test PASSED in OpenBSD 6.4 + GCC 4.2.1.
Test PASSED in NetBSD 8.0 + GCC 5.5.0.
Test **FAILED** in Debian GNU/Hurd 9 + GCC 6.3.0

**Comment by lautis0503** [comment]
Test PASSED in Debian GNU/Hurd 9 + GCC 6.3.0 now.

**Pull request merged**
